### ISSUE TITLE
Returns an error

### ISSUE THREAD

**Issue by qoft** [diamondburned/mass-shootings-count#1]
```json
{
	"Error": "watcher value unfetched"
}
```
In the json api
Recreate:
Fetch `https://shootings.diamondb.xyz/` Using the `Accept: application/json` headers

```
Error: cannot get page 294: cannot do request: Get "https://www.gunviolencearchive.org/reports/mass-shooting?page=294": context deadline exceeded
```
In the normal link
Recreate:
Fetch `https://shootings.diamondb.xyz/` in your web browser

**Comment by diamondburned** [comment]
Made commit 8126fbf to fix this. I'm deploying it now.

**Comment by diamondburned** [comment]
Deployed the fix. Thanks for the issue.
